# Generated by Django 3.0.2 on 2020-05-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stem', '0010_auto_20200523_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='last_school_year_com',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='school_year1',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='school_year2',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4),
        ),
    ]
