# Generated by Django 3.0.2 on 2020-05-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stem', '0012_auto_20200524_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='d1_walking',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
