# Generated by Django 3.0.2 on 2020-05-24 09:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stem', '0014_auto_20200524_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='certify',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='d3_elder_siblings',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='d3_extended_members',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='d3_grandparents',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='d3_independent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='d3_none',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='d3_others',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='d3_parents_or_guardians',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='d4_basic_cp',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='d4_cable_tv',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='d4_desktop',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='d4_laptop',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='d4_noncable_tv',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='d4_none',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='d4_others',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='d4_radio',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='d4_smartphone',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='d4_tablet',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='d6_computer_shop',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='d6_none',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='d6_other_places',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='d6_own_broadband_internet',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='d6_own_mobile_data',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='d7_f2f_w_modalities',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='d7_modular',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='d7_ol_learning',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='d7_others',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='d7_radio',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='d7_tv',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='d8_con_other_activities',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='d8_difficulty_independent_learning',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='d8_distractions',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='d8_health_conditions',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='d8_hi_elec_consump',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='d8_insufficient_load',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='d8_lack_gadgets',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='d8_others',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='d8_unstable_internet',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student_info',
            name='grade_1',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='grade_10',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='grade_11',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='grade_12',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='grade_2',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='grade_3',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='grade_4',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='grade_5',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='grade_6',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='grade_7',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='grade_8',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='grade_9',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='have_internet',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='kinder',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='others',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
