# Generated by Django 3.0.2 on 2020-05-24 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stem', '0016_auto_20200524_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='birthdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
