# Generated by Django 3.0.2 on 2020-05-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stem', '0017_auto_20200524_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='birthdate',
            field=models.DateTimeField(),
        ),
    ]
