# Generated by Django 3.0.2 on 2020-05-26 05:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stem', '0019_remove_student_info_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='date_enrol',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
