# Generated by Django 3.0.2 on 2020-05-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stem', '0022_auto_20200526_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='signature',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='student_signature'),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='track',
            field=models.CharField(blank=True, choices=[('', ''), ('Academic Track', 'Academic Track'), ('Technical-Vocational-Livelihood', 'Technical-Vocational-Livelihood')], max_length=100, null=True),
        ),
    ]
