# Generated by Django 3.0.2 on 2020-05-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stem', '0023_auto_20200527_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='signature',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
