# Generated by Django 3.0.2 on 2020-05-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stem', '0024_auto_20200527_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='JSignatureModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_date', models.DateTimeField(blank=True, null=True, verbose_name='Signature date')),
                ('signature', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='student_info',
            name='signature',
        ),
    ]
