# Generated by Django 3.0.2 on 2020-05-28 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stem', '0025_auto_20200527_1000'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JSignatureModel',
        ),
    ]
